import {
  Combine,
  Scissors,
  FileDown,
  RotateCw,
  Lock,
  Unlock,
  Stamp,
  Image,
  FileImage,
  FileSpreadsheet,
  Presentation,
  FilePenLine,
  Signature,
  Send,
  ScanText,
  Type,
  CaseSensitive,
  FileCode,
  FileOutput,
  Eraser,
  ShieldAlert,
} from "lucide-react";

export const pdfTools = [
  {
    id: 1,
    title: "Merge PDF",
    description: "Combine multiple PDFs into one.",
    icon: Combine,
    href: "/pdf-tools/merge-pdf",
    category: "Edit",
    popular: true,
  },
  {
    id: 2,
    title: "Split PDF",
    description: "Split PDF into multiple files.",
    icon: Scissors,
    href: "/pdf-tools/split",
    category: "Edit",
    popular: true,
  },
  {
    id: 3,
    title: "Compress PDF",
    description: "Reduce PDF file size.",
    icon: FileDown,
    href: "/pdf-tools/compress-pdf",
    category: "Optimize",
    popular: true,
  },
  {
    id: 4,
    title: "Rotate PDF",
    description: "Rotate PDF pages.",
    icon: RotateCw,
    href: "/pdf-tools/rotate",
    category: "Edit",
  },
  {
    id: 5,
    title: "Protect PDF",
    description: "Add password protection.",
    icon: Lock,
    href: "/pdf-tools/protect-pdf",
    category: "Security",
  },
  {
    id: 6,
    title: "Unlock PDF",
    description: "Remove PDF password.",
    icon: Unlock,
    href: "/pdf-tools/unlock-pdf",
    category: "Security",
  },
  {
    id: 7,
    title: "Watermark PDF",
    description: "Add watermark to PDF.",
    icon: Stamp,
    href: "/pdf-tools/watermark",
    category: "Edit",
  },
  {
    id: 8,
    title: "JPG to PDF",
    description: "Convert JPG into PDF.",
    icon: Image,
    href: "/pdf-tools/jpg-to-pdf",
    category: "Convert",
  },
  {
    id: 9,
    title: "PDF to JPG",
    description: "Convert PDF pages to JPG.",
    icon: FileImage,
    href: "/pdf-tools/pdf-to-jpg",
    category: "Convert",
  },
  {
    id: 11,
    title: "Excel to PDF",
    description: "Convert XLSX to PDF.",
    icon: FileSpreadsheet,
    href: "/pdf-tools/excel-to-pdf",
    category: "Convert",
  },
  {
    id: 29,
    title: "PDF to Excel",
    description: "Extract PDF tables into Excel.",
    icon: FileSpreadsheet,
    href: "/pdf-tools/pdf-to-excel",
    category: "Convert",
  },
  {
    id: 12,
    title: "PowerPoint to PDF",
    description: "Convert PPT to PDF.",
    icon: Presentation,
    href: "/pdf-tools/powerpoint-to-pdf",
    category: "Convert",
  },
  {
    id: 13,
    title: "Page Numbers",
    description: "Add page numbers to PDF.",
    icon: FilePenLine,
    href: "/pdf-tools/page-numbers",
    category: "Edit",
  },
  {
    id: 14,
    title: "PDF to PPT",
    description: "Convert PDF files to PowerPoint.",
    icon: Presentation,
    href: "/pdf-tools/pdf-to-ppt",
    category: "Convert",
  },
  {
    id: 15,
    title: "TXT to PDF",
    description: "Convert text files into PDF.",
    icon: Type,
    href: "/pdf-tools/txt-to-pdf",
    category: "Convert",
  },
  {
    id: 16,
    title: "HTML to PDF",
    description: "Convert HTML documents into PDF.",
    icon: FileCode,
    href: "/pdf-tools/html-to-pdf",
    category: "Convert",
  },
  {
    id: 17,
    title: "PDF Editor",
    description: "Add text, images, and drawings.",
    icon: FilePenLine,
    href: "/pdf-tools/edit-pdf",
    category: "Edit",
  },
  {
    id: 18,
    title: "Sign PDF",
    description: "Add signatures, initials, dates and text to a PDF.",
    icon: Signature,
    href: "/sign-pdf",
    category: "Security",
    popular: true,
  },
  {
    id: 19,
    title: "Sign Request",
    description: "Request signatures from others.",
    icon: Send,
    href: "/pdf-tools/sign-request",
    category: "Security",
  },
  {
    id: 20,
    title: "OCR PDF",
    description: "Extract text from scanned PDFs.",
    icon: ScanText,
    href: "/pdf-tools/ocr",
    category: "Convert",
  },
  {
    id: 21,
    title: "Word Counter",
    description: "Count words and characters.",
    icon: Type,
    href: "/pdf-tools/word-counter",
    category: "Utility",
  },
  {
    id: 22,
    title: "Case Converter",
    description: "Convert text letter case.",
    icon: CaseSensitive,
    href: "/pdf-tools/case-converter",
    category: "Utility",
  },
  {
    id: 23,
    title: "Metadata Remover",
    description: "Remove document metadata.",
    icon: Eraser,
    href: "/pdf-tools/metadata-remover",
    category: "Security",
  },
  {
    id: 24,
    title: "Redact Document",
    description: "Hide sensitive document content.",
    icon: ShieldAlert,
    href: "/pdf-tools/redact-document",
    category: "Security",
  },
  {
    id: 28,
    title: "PDF to Word",
    description: "Convert PDF to editable Word document.",
    icon: FileOutput,
    href: "/pdf-tools/pdf-to-word",
    category: "Convert",
  },
];