import {
  Combine,
  Scissors,
  FileDown,
  RotateCw,
  Lock,
  Unlock,
  Stamp,
  Image,
  FileImage,
  FileText,
  FileSpreadsheet,
  Presentation,
} from "lucide-react";

export const pdfTools = [
  {
    id: 1,
    title: "Merge PDF",
    description: "Combine multiple PDFs into one.",
    icon: Combine,
    href: "/pdf-tools/merge-pdf",
    category: "Edit",
    popular: true,
  },
  {
    id: 2,
    title: "Split PDF",
    description: "Split PDF into multiple files.",
    icon: Scissors,
    href: "/pdf-tools/split",
    category: "Edit",
    popular: true,
  },
  {
    id: 3,
    title: "Compress PDF",
    description: "Reduce PDF file size.",
    icon: FileDown,
    href: "/pdf-tools/compress-pdf",
    category: "Optimize",
    popular: true,
  },
  {
    id: 4,
    title: "Rotate PDF",
    description: "Rotate PDF pages.",
    icon: RotateCw,
    href: "/pdf-tools/rotate",
    category: "Edit",
  },
  {
    id: 5,
    title: "Protect PDF",
    description: "Add password protection.",
    icon: Lock,
    href: "/pdf-tools/protect-pdf",
    category: "Security",
  },
  {
    id: 6,
    title: "Unlock PDF",
    description: "Remove PDF password.",
    icon: Unlock,
    href: "/pdf-tools/unlock-pdf",
    category: "Security",
  },
  {
    id: 7,
    title: "Watermark PDF",
    description: "Add watermark to PDF.",
    icon: Stamp,
    href: "/pdf-tools/watermark",
    category: "Edit",
  },
  {
    id: 8,
    title: "JPG to PDF",
    description: "Convert JPG into PDF.",
    icon: Image,
    href: "/pdf-tools/jpg-to-pdf",
    category: "Convert",
  },
  {
    id: 9,
    title: "PDF to JPG",
    description: "Convert PDF pages to JPG.",
    icon: FileImage,
    href: "/pdf-tools",
    category: "Convert",
  },
  {
    id: 10,
    title: "PDF to Word",
    description: "Convert PDF to DOCX.",
    icon: FileText,
    href: "/pdf-tools",
    category: "Convert",
  },
  {
    id: 11,
    title: "Excel to PDF",
    description: "Convert XLSX to PDF.",
    icon: FileSpreadsheet,
    href: "/pdf-tools",
    category: "Convert",
  },
  {
    id: 12,
    title: "PowerPoint to PDF",
    description: "Convert PPT to PDF.",
    icon: Presentation,
    href: "/pdf-tools",
    category: "Convert",
  },
];