import type { GovernmentService } from "./types";

export const governmentServices: GovernmentService[] = [
  {
    id: 1,
    title: "PAN Card",
    description: "New Apply, Correction & Reprint",
    icon: "🪪",
    href: "/service/pan-card",
    category: "Identity",
    popular: true,
  },
  {
    id: 2,
    title: "Aadhaar Card",
    description: "Update, Download & PVC Card",
    icon: "🆔",
    href: "/service/aadhaar",
    category: "Identity",
    popular: true,
  },
  {
    id: 3,
    title: "Passport",
    description: "Fresh & Renewal Application",
    icon: "🛂",
    href: "/service/passport",
    category: "Identity",
  },
  {
    id: 4,
    title: "Driving Licence",
    description: "Apply & Renewal",
    icon: "🚗",
    href: "/service/driving-licence",
    category: "Transport",
  },
  {
    id: 5,
    title: "Income Certificate",
    description: "Online Apply",
    icon: "📄",
    href: "/service/income-certificate",
    category: "Certificate",
  },
  {
    id: 6,
    title: "Caste Certificate",
    description: "Apply & Download",
    icon: "📜",
    href: "/service/caste-certificate",
    category: "Certificate",
  },
  {
    id: 7,
    title: "Domicile Certificate",
    description: "Residence Certificate",
    icon: "🏠",
    href: "/service/domicile",
    category: "Certificate",
  },
  {
    id: 8,
    title: "Birth Certificate",
    description: "New Registration & Download",
    icon: "👶",
    href: "/service/birth-certificate",
    category: "Certificate",
  },
  {
    id: 9,
    title: "Death Certificate",
    description: "Registration & Certified Copy",
    icon: "⚰️",
    href: "/service/death-certificate",
    category: "Certificate",
  },
  {
    id: 10,
    title: "Ayushman Bharat Card",
    description: "Eligibility & Card Download",
    icon: "❤️",
    href: "/service/ayushman-card",
    category: "Health",
    popular: true,
  },
  {
    id: 11,
    title: "Scholarship",
    description: "Central & State Schemes",
    icon: "🎓",
    href: "/service/scholarship",
    category: "Education",
  },
  {
    id: 12,
    title: "CSC Services",
    description: "Digital Seva Portal",
    icon: "🏛️",
    href: "/service/csc",
    category: "CSC",
  },
  {
    id: 13,
    title: "Ration Card",
    description: "New Apply & Correction",
    icon: "🍚",
    href: "/service/ration-card",
    category: "Identity",
  },
  {
    id: 14,
    title: "e-Shram Card",
    description: "Registration & Update",
    icon: "🦺",
    href: "/service/e-shram",
    category: "Health",
  },
  {
    id: 15,
    title: "PM Kisan",
    description: "Registration & Status",
    icon: "🌾",
    href: "/service/pm-kisan",
    category: "CSC",
  },
  {
    id: 16,
    title: "Labour Card",
    description: "Apply & Renewal",
    icon: "👷",
    href: "/service/labour-card",
    category: "Health",
  },
  {
    id: 17,
    title: "Voter ID",
    description: "Apply, Update & Download",
    icon: "🗳️",
    href: "/service/voter-id",
    category: "Identity",
  },
  {
    id: 18,
    title: "Marriage Certificate",
    description: "Online Registration",
    icon: "💍",
    href: "/service/marriage-certificate",
    category: "Certificate",
  },
  {
    id: 19,
    title: "Police Verification",
    description: "Online Verification Request",
    icon: "👮",
    href: "/service/police-verification",
    category: "Certificate",
  },
];