import type { DigiDeskService } from "./types";

export const DIGIDESK_SERVICES: DigiDeskService[] = [
  {
    id: "pdf-compress",
    name: "Compress PDF",
    category: "PDF Tools",
    aliases: [
      "compress pdf",
      "reduce pdf size",
      "pdf compression",
      "pdf chhota karna",
      "pdf ka size kam karna",
      "reduce pdf",
      "pdf size reduce",
      "pdf ko chhota karna",
      "pdf size kam",
      "compress this pdf",
      "pdf compress",
      "pdf ko compress karna",
    ],
    description: "Reduce the file size of a PDF while keeping the document usable.",
    route: "/pdf-tools/compress-pdf",
    requiresFileUpload: true,
    supportedFileTypes: ["PDF"],
    workflowSteps: [
      "Open the Compress PDF tool.",
      "Upload the PDF file you want to compress.",
      "Choose the compression level or keep the default setting.",
      "Click Compress PDF and wait for processing to finish.",
      "Review the reduced-size output, then download the compressed file.",
    ],
    processingDescription: "The PDF is analyzed and optimized to reduce file size while preserving the document content and layout where possible.",
    resultDescription: "You get a lighter PDF file with size indicators and a downloadable output.",
    downloadDescription: "Click Download to save the compressed PDF to your device.",
    relatedTools: ["pdf-merge", "pdf-ocr", "pdf-metadata-remover"],
  },
  {
    id: "pdf-merge",
    name: "Merge PDF",
    category: "PDF Tools",
    aliases: [
      "merge pdf",
      "combine pdf",
      "join pdf files",
      "merge multiple pdf",
      "pdf ko ek saath karna",
      "combine pdfs",
      "pdf merge",
      "pdf files merge",
    ],
    description: "Combine multiple PDF files into one organized document.",
    route: "/pdf-tools/merge-pdf",
    requiresFileUpload: true,
    supportedFileTypes: ["PDF"],
    workflowSteps: [
      "Open the Merge PDF tool.",
      "Upload the PDF files you want to join.",
      "Arrange them in the correct order.",
      "Click Merge PDF and wait for processing.",
      "Download the combined output file.",
    ],
    processingDescription: "The selected PDF files are combined in the chosen order to create one final document.",
    resultDescription: "You receive a single merged PDF that contains all uploaded pages in sequence.",
    downloadDescription: "Download the merged file from the result page once the merge is complete.",
    relatedTools: ["pdf-split", "pdf-organize", "pdf-page-numbers"],
  },
  {
    id: "pdf-split",
    name: "Split PDF",
    category: "PDF Tools",
    aliases: [
      "split pdf",
      "divide pdf",
      "separate pdf pages",
      "pdf ko split karna",
      "split document",
      "break pdf into pages",
      "pdf split",
      "page wise split",
    ],
    description: "Divide a PDF into separate pages or ranges.",
    route: "/pdf-tools/split",
    requiresFileUpload: true,
    supportedFileTypes: ["PDF"],
    workflowSteps: [
      "Open the Split PDF tool.",
      "Upload the source PDF.",
      "Choose split ranges or pages you want to separate.",
      "Run the split process.",
      "Download each resulting file or the combined output.",
    ],
    processingDescription: "The tool creates separate outputs from the selected PDF ranges or page selections.",
    resultDescription: "You get split PDF files based on the requested page or range selection.",
    downloadDescription: "Use the download buttons on the result page to save each generated PDF.",
    relatedTools: ["pdf-merge", "pdf-extract-pages", "pdf-organize"],
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    category: "PDF Tools",
    aliases: [
      "pdf to word",
      "convert pdf to word",
      "pdf ko word me convert",
      "pdf to doc",
      "editable word file",
      "word file banane",
      "pdf ko docx me",
      "pdf to docx",
    ],
    description: "Convert a PDF into an editable Word document.",
    route: "/pdf-tools/pdf-to-word",
    requiresFileUpload: true,
    supportedFileTypes: ["PDF"],
    workflowSteps: [
      "Open the PDF to Word tool.",
      "Upload the PDF file to be converted.",
      "Select conversion options if shown in the tool.",
      "Click Convert PDF to Word and wait for the conversion to finish.",
      "Download the generated Word file.",
    ],
    processingDescription: "The PDF is parsed and converted into an editable DOCX/Word document while preserving the structure as closely as possible.",
    resultDescription: "You receive an editable Word file that can be opened in Microsoft Word or compatible editors.",
    downloadDescription: "Download the DOCX file from the output section and save it on your device.",
    relatedTools: ["pdf-to-excel", "pdf-to-ppt", "pdf-ocr"],
  },
  {
    id: "pdf-ocr",
    name: "OCR PDF",
    category: "PDF Tools",
    aliases: [
      "ocr pdf",
      "pdf ocr",
      "scanned pdf text extract",
      "make pdf searchable",
      "pdf ko searchable banana",
      "extract text from pdf",
      "ocr",
      "read scanned pdf",
    ],
    description: "Extract text from scanned or image-based PDFs so they become searchable and selectable.",
    route: "/pdf-tools/ocr",
    requiresFileUpload: true,
    supportedFileTypes: ["PDF"],
    workflowSteps: [
      "Open the OCR PDF tool.",
      "Upload the scanned PDF file.",
      "Choose the OCR language or language combination.",
      "Start the OCR process and wait for the progress to complete.",
      "Review the searchable result and download the OCR-ed PDF.",
    ],
    processingDescription: "The scanned PDF pages are processed with OCR to recognize text and produce a searchable output file.",
    resultDescription: "You get a searchable, selectable PDF that can be copied and searched more easily.",
    downloadDescription: "Download the processed PDF from the result panel once OCR completes.",
    relatedTools: ["pdf-to-word", "pdf-redact", "pdf-sign"],
  },
  {
    id: "pdf-sign",
    name: "Sign PDF",
    category: "PDF Tools",
    aliases: [
      "sign pdf",
      "pdf sign",
      "add signature to pdf",
      "digital signature",
      "pdf par sign karna",
      "signature on pdf",
      "add signature",
    ],
    description: "Add signatures, initials, dates, or text to a PDF document.",
    route: "/sign-pdf",
    requiresFileUpload: true,
    supportedFileTypes: ["PDF"],
    workflowSteps: [
      "Open the Sign PDF tool.",
      "Upload the PDF document to sign.",
      "Choose the signature or text placement options shown in the tool.",
      "Apply the signature and wait for the document to finish processing.",
      "Download the signed PDF.",
    ],
    processingDescription: "The tool places the chosen signature or text on the selected PDF pages and creates a signed document file.",
    resultDescription: "You receive a signed PDF ready for sharing or storing.",
    downloadDescription: "Use the final download button to save the signed file to your computer.",
    relatedTools: ["pdf-redact", "pdf-protect", "pdf-ocr"],
  },
  {
    id: "pdf-redact",
    name: "Redact Document",
    category: "PDF Tools",
    aliases: [
      "redact pdf",
      "hide sensitive text",
      "remove confidential content",
      "pdf ko redact karna",
      "document redaction",
      "redact document",
      "sensitive info hide",
    ],
    description: "Hide or remove sensitive information from a PDF document.",
    route: "/pdf-tools/redact-document",
    requiresFileUpload: true,
    supportedFileTypes: ["PDF"],
    workflowSteps: [
      "Open the Redact Document tool.",
      "Upload the PDF file you want to protect.",
      "Mark the text or areas that must be hidden.",
      "Apply redaction and wait for processing to finish.",
      "Download the redacted PDF.",
    ],
    processingDescription: "Sensitive content is marked and removed from the output so the private information is no longer visible in the final PDF.",
    resultDescription: "You receive a cleaned PDF with the selected content removed or blacked out.",
    downloadDescription: "Download the final redacted document from the result section.",
    relatedTools: ["pdf-sign", "pdf-protect", "pdf-ocr"],
  },
  {
    id: "pdf-protect",
    name: "Protect PDF",
    category: "PDF Tools",
    aliases: [
      "protect pdf",
      "lock pdf",
      "password pdf",
      "pdf ko password banana",
      "pdf password",
      "encrypt pdf",
    ],
    description: "Add document protection and password security to a PDF.",
    route: "/pdf-tools/protect-pdf",
    requiresFileUpload: true,
    supportedFileTypes: ["PDF"],
    workflowSteps: [
      "Open the Protect PDF tool.",
      "Upload the PDF file you want to secure.",
      "Set the password or protection option shown in the tool.",
      "Apply protection and wait for the file to finish processing.",
      "Download the protected PDF.",
    ],
    processingDescription: "Security settings are applied to the PDF so the document is encrypted or safeguarded with chosen protection options.",
    resultDescription: "You receive a protected PDF that is secured with the selected settings.",
    downloadDescription: "Click the output download link to save the protected document.",
    relatedTools: ["pdf-sign", "pdf-redact", "pdf-unlock"],
  },
  {
    id: "image-compress",
    name: "Compress Image",
    category: "Image Tools",
    aliases: [
      "compress image",
      "reduce image size",
      "image compression",
      "image ko chhota karna",
      "image size reduce",
      "jpg compress",
      "png compress",
      "image file size reduce",
    ],
    description: "Reduce the file size of a JPG, PNG, or other image while preserving the visual quality.",
    route: "/image-tools/compress-image",
    requiresFileUpload: true,
    supportedFileTypes: ["JPG", "PNG", "WEBP", "JPEG"],
    workflowSteps: [
      "Open the Compress Image tool.",
      "Upload the image file.",
      "Choose the output format or quality if the tool offers it.",
      "Click Compress and wait for processing to finish.",
      "Review the optimized image and download it.",
    ],
    processingDescription: "The selected image is optimized by reducing its output size and quality settings to create a smaller file.",
    resultDescription: "You get a compressed image file that is lighter to store or share.",
    downloadDescription: "Download the optimized image from the result section.",
    relatedTools: ["image-convert", "passport-photo", "image-resize"],
  },
  {
    id: "image-convert",
    name: "Convert Image",
    category: "Image Tools",
    aliases: [
      "convert image",
      "jpg to png",
      "png to jpg",
      "image format convert",
      "image ko format change",
      "convert png to jpeg",
      "jpeg to png",
      "image format change",
    ],
    description: "Convert images between common formats like JPG, PNG, and WEBP.",
    route: "/image-tools/convert-image",
    requiresFileUpload: true,
    supportedFileTypes: ["JPG", "PNG", "WEBP", "JPEG"],
    workflowSteps: [
      "Open the Convert Image tool.",
      "Upload the source image.",
      "Choose the target output format.",
      "Start conversion and wait for the result.",
      "Download the converted image file.",
    ],
    processingDescription: "The tool re-encodes the uploaded image into the selected format and generates the output file.",
    resultDescription: "You receive a converted image in the desired file format.",
    downloadDescription: "Save the output image using the download button on the page.",
    relatedTools: ["image-compress", "passport-photo", "image-to-pdf"],
  },
  {
    id: "image-remove-background",
    name: "Remove Background",
    category: "Image Tools",
    aliases: [
      "remove background",
      "background remover",
      "image background remove",
      "photo background remove",
      "bg remove",
      "image ka background remove",
      "background removal",
      "remove bg",
    ],
    description: "Remove the background from an image and create a cleaner cutout version.",
    route: "/image-tools/remove-background",
    requiresFileUpload: true,
    supportedFileTypes: ["JPG", "PNG", "WEBP", "JPEG"],
    workflowSteps: [
      "Open the Remove Background tool.",
      "Upload the image whose background you want to remove.",
      "Let the tool process the image and generate the cutout.",
      "Review the background-removed result.",
      "Download the processed image.",
    ],
    processingDescription: "AI or image processing is used to detect the subject and remove the background from the uploaded photo.",
    resultDescription: "You receive a cleaner cutout image with the background removed.",
    downloadDescription: "Use the download button to save the edited transparent or cutout image.",
    relatedTools: ["passport-photo", "image-compress", "image-to-pdf"],
  },
  {
    id: "passport-photo",
    name: "Passport Photo",
    category: "Image Tools",
    aliases: [
      "passport photo",
      "passport size photo",
      "passport photo maker",
      "photo for passport",
      "passport ka photo",
      "make passport photo",
      "visa photo",
    ],
    description: "Generate a print-ready passport or visa photo sheet from a source image.",
    route: "/image-tools/passport-photo",
    requiresFileUpload: true,
    supportedFileTypes: ["JPG", "PNG", "JPEG"],
    workflowSteps: [
      "Open the Passport Photo tool.",
      "Upload a clear front-facing face photo.",
      "Select the passport or visa target size and output format.",
      "Generate the sheet and wait for processing.",
      "Download the created photo sheet for printing.",
    ],
    processingDescription: "The tool creates a printable photo sheet with the required dimensions and layout for passport or visa use.",
    resultDescription: "You receive a printable photo sheet with the required layout and dimensions for official use.",
    downloadDescription: "Download the generated JPG or PDF sheet and print it if required.",
    relatedTools: ["image-compress", "image-convert", "image-remove-background"],
  },
  {
    id: "government-pan-card",
    name: "PAN Card",
    category: "Government Services",
    aliases: [
      "pan card",
      "pan card apply",
      "pan card correction",
      "new pan",
      "pan ka form",
      "pan apply",
      "pan card form",
      "income tax pan",
    ],
    description: "Apply for a new PAN card, correction, or PAN-related service guidance.",
    route: "/service/pan-card",
    requiresFileUpload: false,
    workflowSteps: [
      "Open the PAN Card service page.",
      "Check the required documents and eligibility details on the page.",
      "Prepare your Aadhaar, photo, and proof details as requested.",
      "Follow the service instructions to apply or update PAN.",
      "Complete the process and track or download the final result as provided by the service flow.",
    ],
    processingDescription: "The PAN service page outlines the required information, supporting documents, fees, and processing workflow for PAN-related applications.",
    resultDescription: "You get the required service guidance and the official process path for applying or updating PAN data.",
    downloadDescription: "Use the service flow or final application page to view/download the issued PAN-related document or outcome.",
    relatedTools: ["government-csc", "government-passport"],
  },
  {
    id: "government-csc",
    name: "CSC Services",
    category: "Government Services",
    aliases: [
      "csc services",
      "jan seva",
      "jan seva kendra",
      "digital seva",
      "csc",
      "csc seva",
      "online government service",
      "government service help",
    ],
    description: "Get guidance for CSC and Jan Seva-related digital service requests.",
    route: "/service/csc",
    requiresFileUpload: false,
    workflowSteps: [
      "Open the CSC Services page.",
      "Select the relevant service category or the service you need help with.",
      "Check the listed documents, eligibility, and steps for the service.",
      "Follow the public service guidance and submit through the official process.",
      "Track or download any issued output available in the service flow.",
    ],
    processingDescription: "The CSC page provides the official service category and step-by-step guidance for resident-facing digital services and Jan Seva support.",
    resultDescription: "You receive the relevant service guidance and the path to complete the requested CSC or Jan Seva process.",
    downloadDescription: "Download or submit the required output only through the official service flow provided on the page.",
    relatedTools: ["government-pan-card", "government-passport"],
  },
  {
    id: "government-passport",
    name: "Passport Services",
    category: "Government Services",
    aliases: [
      "passport",
      "passport apply",
      "passport reissue",
      "passport renewal",
      "passport service",
      "passport kaise bharein",
      "new passport",
    ],
    description: "Get guidance for passport application, renewal, and related service steps.",
    route: "/service/passport",
    requiresFileUpload: false,
    workflowSteps: [
      "Open the Passport service page.",
      "Check the required documents, eligibility, and application flow.",
      "Prepare the information and supporting documents mentioned in the service page.",
      "Follow the official application instructions through the service process.",
      "Use the service result or tracking flow for completion or download where available.",
    ],
    processingDescription: "The passport service page explains the application steps, required documents, and the public process for Passport-related service requests.",
    resultDescription: "You get the official service path and supporting details for passport application or renewal guidance.",
    downloadDescription: "Follow the official service flow to download or track the final passport-related output if the service provides it.",
    relatedTools: ["government-pan-card", "government-csc"],
  },
];

export const DIGIDESK_SERVICE_MAP = Object.fromEntries(
  DIGIDESK_SERVICES.map((service) => [service.id, service]),
) as Record<string, DigiDeskService>;
